# Generated by Django 6.0.4 on 2026-07-12 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, verbose_name="رقم الهاتف العُماني / Omani Phone"
                    ),
                ),
                (
                    "commercial_register",
                    models.CharField(
                        max_length=50,
                        verbose_name="رقم السجل التجاري (CR) / Commercial Register",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="مؤسسة عُمانية ناشئة",
                        max_length=150,
                        verbose_name="اسم الشركة / SME Name",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم / User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(
                        upload_to="excel_files/",
                        verbose_name="ملف البيانات المحاسبية / Accounting File",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الرفع / Uploaded At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم / User",
                    ),
                ),
            ],
        ),
    ]
