# Generated by Django 6.0.7 on 2026-07-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                ("product", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.projectfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
