# Generated by Django 6.0.7 on 2026-07-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_userfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("pharmacy", "صيدلية (Pharmacy)"),
                    ("real_estate", "عقارات (Real Estate)"),
                    ("retail", "تجارة التجزئة (Retail)"),
                    ("fnb", "مطاعم ومقاهي (F&B)"),
                    ("other", "أخرى (Other)"),
                ],
                default="other",
                max_length=20,
                verbose_name="نوع المشروع / Project Type",
            ),
        ),
    ]
