# Generated by Django 6.0.7 on 2026-08-07 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_announcement_aiusagelog_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("success", "نجاح"),
                            ("warning", "تحذير"),
                            ("info", "معلومة"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الإشعار"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
        ),
    ]
