# Generated by Django 6.0.7 on 2026-08-10 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_agentmemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الشذوذ')),
                ('description', models.TextField(verbose_name='التفاصيل والتأثير')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='توصية بصيرة المقترحة')),
                ('severity', models.CharField(choices=[('critical', 'حرج / عالي الخطورة'), ('warning', 'تحذير / متوسط'), ('info', 'ملحوظة / منخفض')], default='warning', max_length=20)),
                ('metric_name', models.CharField(default='sales', max_length=100, verbose_name='المؤشر المتأثر')),
                ('change_percent', models.FloatField(default=0.0, verbose_name='نسبة التغير')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='تم التجاهل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.projectfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(max_length=50, verbose_name='الأسبوع')),
                ('summary_text', models.TextField(verbose_name='الملخص التنفيذي')),
                ('top_risks', models.JSONField(default=list, verbose_name='أهم المخاطر')),
                ('top_opportunities', models.JSONField(default=list, verbose_name='أهم الفرص')),
                ('action_plan', models.JSONField(default=list, verbose_name='خطة العمل المقترحة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_digests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='SalesGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12, verbose_name='مستهدف الإيراد')),
                ('target_profit', models.DecimalField(decimal_places=2, default=1500.0, max_digits=12, verbose_name='مستهدف صافي الربح')),
                ('month', models.CharField(help_text='YYYY-MM', max_length=7, verbose_name='الشهر المستهدف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
