# Generated by Django 6.0.7 on 2026-08-10 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_anomalyalert_weeklydigest_salesgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardroomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300, verbose_name='موضوع أو قرار الجلسة')),
                ('debate_history', models.JSONField(default=list, verbose_name='سجل حوار ومداخلات الوكلاء')),
                ('final_resolution', models.TextField(blank=True, null=True, verbose_name='القرار النهائي المعتمد')),
                ('action_items', models.JSONField(default=list, verbose_name='خطة العمل التنفيذية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardroom_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الوكيل')),
                ('role_title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي / التخصص')),
                ('department', models.CharField(default='general', max_length=100, verbose_name='القسم / المجال')),
                ('icon', models.CharField(default='bot', max_length=50, verbose_name='أيقونة الوكيل (Lucide Icon)')),
                ('color', models.CharField(default='indigo', max_length=50, verbose_name='لون الثيم')),
                ('system_prompt', models.TextField(verbose_name='توجيهات النظام ونبرة الحديث')),
                ('knowledge_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات معرفية ومستندات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_agents', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
