# Generated by Django 6.0.7 on 2026-08-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_boardroomsession_customagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='هل الاشتراك نشط؟ / Is Subscribed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'فترة تجريبية (Trial)'), ('starter', 'باقة الانطلاق (Starter)'), ('growth', 'باقة النمو (Growth)'), ('enterprise', 'باقة المؤسسات (Enterprise)')], default='trial', max_length=50, verbose_name='باقة الاشتراك / Subscription Plan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء الفترة التجريبية / Trial Start Date'),
        ),
    ]
