# Generated by Django 6.0.4 on 2026-08-22 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_profile_is_subscribed_profile_subscription_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='محادثة جماعية جديدة', max_length=250, verbose_name='عنوان الجلسة')),
                ('selected_agents', models.JSONField(default=list, verbose_name='الوكلاء المختارون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_threads', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'مستخدم'), ('assistant', 'وكيل ذكي'), ('system', 'نظام')], default='assistant', max_length=20)),
                ('agent_id', models.CharField(default='general', max_length=50, verbose_name='معرف الوكيل')),
                ('agent_name', models.CharField(default='بصيرة', max_length=150, verbose_name='اسم الوكيل')),
                ('agent_avatar', models.CharField(default='sparkles', max_length=50, verbose_name='أيقونة الوكيل')),
                ('agent_color', models.CharField(default='indigo', max_length=50, verbose_name='لون الوكيل')),
                ('content', models.TextField(verbose_name='نص الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.committeethread', verbose_name='جلسة المحادثة')),
            ],
        ),
    ]
